name: LightningWands
author: nbdSteve
version: 3.1.4
main: dev.nuer.strike.LightningWands
commands:
  lw:
    usage: /<command>
    description: Type '/lw help' for command help.
  lightning:
    usage: /<command>
    description: Type '/lw help' for command help.