name: LightningWands
version: 3.1.4-[MC-1.13+]
main: dev.nuer.strike.LightningWands
author: Nuer
api-version: 1.13
commands:
  lw:
    usage: /<command>
    description: Type '/lw help' for command help.
  lightning:
    usage: /<command>
    description: Type '/lw help' for command help.